# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed0c32eab2d8f213bf52b42706d93debce0fda577a9d581dbff219dbb99269615b0ab8d61df5403a469c563f3deb9b3b06c909ff3e5f51ff71b468d6eeff1b6a

test:
  secret_key_base: b02569a8fa06c341a0a6324eed6209f5033286702aa232b61d290377dcfcda46e91179c8917e69a3f20f1053fac989f85a661968b913d63884763fe892250460

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
